name: 'Install Istio in an existing Kubernetes cluster'
description: 'This action installs Istio in an existing Kubernetes cluster'
author: 'Hai Huang'
branding:
  icon: anchor
  color: blue
inputs:
  istio version:
    description: 'Istio version to install'
    required: false
    default: '1.6.3'
  istio profile:
    description: "Istio profile when installing"
    required: false
    default: "demo"
  istio args:
    description: "Istio install parameters"
    required: false
    default: ""
  kubeconfig:
    description: 'Content of ~/.kube/config'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
